"""Reproduce the clarification branch from its retained private base case."""
import argparse,json
from pathlib import Path
p=argparse.ArgumentParser(description=__doc__);p.add_argument('base',type=Path);p.add_argument('output',type=Path);a=p.parse_args()
if a.output.exists():raise ValueError('Use a new output')
c=json.loads(a.base.read_text())
c["scenes"].append({'id': 'clarification', 'deliveries': [{'recipients': ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8'], 'content': 'Before accusations, take a final clarification round. The fixed personality facts on character cards are truthful, shareable facts in this puzzle; they are not invented alibis. The printed clues are reliable. Answer the questions already raised about your own character. Keep involvement in the murder private until the scheduled confession.'}], 'encounters': [{'participants': ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8'], 'turns_each': 2, 'instruction': 'Clarify your OWN fixed character facts against the clue attributes already discussed. First answer outstanding questions about you. State several accurate matches or exclusions from your own card, rather than asking everyone the same questions again. On your second turn, fill remaining gaps instead of repeating your first answer. Do not invent a fact absent from your card. Do not disclose whether you committed the murder.'}]})
c["question"]='Privately identify the guest best supported as the murderer, or say insufficient evidence if the received information genuinely leaves several candidates. Use ALL information you actually received, including attributed reports of printed clue cards and character facts during discussion. Compare candidates against the combined clues. Treat stated fixed personality facts as truthful within this puzzle unless a specific contradiction appears; do not demand proof beyond the game rules. Distinguish an excluded candidate from one whose facts are unknown. Explain your choice consistently with the evidence; do not accuse someone you have just ruled out.'
c["provenance"]["assumptions"]=[x for x in c["provenance"]["assumptions"] if x!="No extra post-hunt discussion"]
c["provenance"]["assumptions"].append('Experimental additional clarification round and explicit cooperative fixed-fact interpretation before assessment; previous128 speeches and host action reused exactly')
a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(c,indent=2)+"\n");a.output.chmod(0o600)
